export const categories = [
  {
    id: "electronics",
    name: "Electronics",
    description: "Flight controllers, ESCs, GPS & stacks",
    icon: "⚡",
    color: "from-blue-500 to-blue-700",
    count: 120,
  },
  {
    id: "fpv",
    name: "FPV Equipment",
    description: "Cameras, goggles, antennas & VTX",
    icon: "📡",
    color: "from-sky-500 to-sky-700",
    count: 95,
  },
  {
    id: "motors",
    name: "Motors",
    description: "Micro, long-range & professional motors",
    icon: "🔄",
    color: "from-indigo-500 to-indigo-700",
    count: 60,
  },
  {
    id: "frames",
    name: "Frames",
    description: "3-inch to 15-inch race & freestyle frames",
    icon: "🔩",
    color: "from-violet-500 to-violet-700",
    count: 45,
  },
  {
    id: "propellers",
    name: "Propellers",
    description: "2-inch to 10+ inch props for all builds",
    icon: "🌀",
    color: "from-blue-400 to-blue-600",
    count: 80,
  },
  {
    id: "battery",
    name: "Battery & Charging",
    description: "LiPo cells, chargers & battery straps",
    icon: "🔋",
    color: "from-cyan-500 to-cyan-700",
    count: 55,
  },
  {
    id: "radio",
    name: "Radio & Receiver",
    description: "Controllers, receivers & RF modules",
    icon: "📻",
    color: "from-teal-500 to-teal-700",
    count: 40,
  },
  {
    id: "accessories",
    name: "Accessories",
    description: "Cables, connectors, tools & more",
    icon: "🔧",
    color: "from-slate-500 to-slate-700",
    count: 200,
  },
];

export const featuredProducts = [
  {
    id: 1,
    name: "F7 Flight Controller Stack",
    category: "Electronics",
    price: 4299,
    originalPrice: 5499,
    rating: 4.8,
    reviews: 124,
    badge: "Best Seller",
    badgeColor: "bg-blue-600",
    inStock: true,
  },
  {
    id: 2,
    name: "2207 2450KV Brushless Motor",
    category: "Motors",
    price: 899,
    originalPrice: 1199,
    rating: 4.9,
    reviews: 312,
    badge: "Top Rated",
    badgeColor: "bg-green-600",
    inStock: true,
  },
  {
    id: 3,
    name: "5 Inch FPV Racing Frame",
    category: "Frames",
    price: 2199,
    originalPrice: 2799,
    rating: 4.7,
    reviews: 89,
    badge: "New",
    badgeColor: "bg-orange-500",
    inStock: true,
  },
  {
    id: 4,
    name: "FPV Camera 1200TVL",
    category: "FPV Equipment",
    price: 1599,
    originalPrice: 1999,
    rating: 4.6,
    reviews: 67,
    badge: "Sale",
    badgeColor: "bg-red-500",
    inStock: true,
  },
  {
    id: 5,
    name: "4S 1500mAh LiPo Battery",
    category: "Battery",
    price: 1299,
    originalPrice: 1599,
    rating: 4.8,
    reviews: 201,
    badge: "Best Seller",
    badgeColor: "bg-blue-600",
    inStock: true,
  },
  {
    id: 6,
    name: "FrSky R9M Long Range Module",
    category: "Radio",
    price: 3499,
    originalPrice: 4299,
    rating: 4.7,
    reviews: 45,
    badge: "New",
    badgeColor: "bg-orange-500",
    inStock: false,
  },
  {
    id: 7,
    name: "5.8GHz FPV Goggles",
    category: "FPV Equipment",
    price: 8999,
    originalPrice: 11999,
    rating: 4.9,
    reviews: 156,
    badge: "Top Rated",
    badgeColor: "bg-green-600",
    inStock: true,
  },
  {
    id: 8,
    name: "5045 Tri-Blade Props (4 pack)",
    category: "Propellers",
    price: 299,
    originalPrice: 399,
    rating: 4.5,
    reviews: 445,
    badge: "Sale",
    badgeColor: "bg-red-500",
    inStock: true,
  },
];

export const blogPosts = [
  {
    id: 1,
    title: "How to Choose the Right Flight Controller for Your Build",
    excerpt: "A complete guide to selecting flight controllers based on your drone type, budget, and performance needs.",
    category: "Guides",
    readTime: "8 min read",
    date: "May 20, 2025",
  },
  {
    id: 2,
    title: "LiPo Battery Safety: What Every Drone Pilot Must Know",
    excerpt: "Essential tips for storing, charging, and handling LiPo batteries safely to avoid fires and extend battery life.",
    category: "Safety",
    readTime: "6 min read",
    date: "May 14, 2025",
  },
  {
    id: 3,
    title: "FPV vs Long-Range: Which System Is Right for You?",
    excerpt: "Compare FPV racing setups with long-range systems to find the perfect configuration for your flying style.",
    category: "Reviews",
    readTime: "10 min read",
    date: "May 8, 2025",
  },
];

export const stats = [
  { label: "Products", value: "1,200+", icon: "📦" },
  { label: "Happy Customers", value: "25,000+", icon: "😊" },
  { label: "Orders Shipped", value: "80,000+", icon: "🚚" },
  { label: "Expert Support", value: "24/7", icon: "💬" },
];

export const testimonials = [
  {
    id: 1,
    name: "Arjun Sharma",
    role: "FPV Racing Pilot",
    text: "ASD Drones has the best selection of FPV gear in India. Fast shipping and quality parts every single time!",
    rating: 5,
    city: "Bengaluru",
  },
  {
    id: 2,
    name: "Priya Patel",
    role: "Aerial Photographer",
    text: "I built my first long-range drone entirely from parts bought at ASD Drones. The team helped me pick the right components.",
    rating: 5,
    city: "Mumbai",
  },
  {
    id: 3,
    name: "Karthik Rao",
    role: "Drone Enthusiast",
    text: "Incredible prices and genuine parts. The blog articles helped me understand what to buy before I placed my first order.",
    rating: 5,
    city: "Hyderabad",
  },
];
